apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/frontend

namespace: globepay-prod

patches:
- path: ./patches/frontend-deployment.yaml

# Create secrets needed for frontend
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: backend-secrets
  literals:
  - jwt-secret=placeholder-jwt-secret
  - database-url=placeholder-db-url