apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/frontend

namespace: globepay-prod

patches:
- path: patches/frontend-deployment.yaml

images:
- name: 907849381252.dkr.ecr.us-east-1.amazonaws.com/globepay-frontend
  newTag: sha-b53dc2e698d12047f67f5bafe3c0a37f7b42b31e