apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/frontend
- ../../base/ingress

namespace: globepay-prod

patchesStrategicMerge:
- ./patches/frontend-deployment.yaml