apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/frontend

namespace: globepay-prod

patches:
- path: patches/frontend-deployment.yaml

images:
- name: 907849381252.dkr.ecr.us-east-1.amazonaws.com/globepay-frontend
  newName: 907849381252.dkr.ecr.us-east-1.amazonaws.com/globepay-frontend
  newTag: 7f0d6d21e9e3e71ca77c91e6e29b40677b05d220
