apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: 907849381252.dkr.ecr.us-east-1.amazonaws.com/globepay-backend:v1.0.1
        command: ["/app/migrate"]
        args: ["up"]
        env:
        - name: DATABASE_URL
          value: "postgresql://globepay:secure_password_here@postgresql.globepay-prod.svc.cluster.local:5432/globepay_prod?sslmode=disable"
      restartPolicy: Never
  backoffLimit: 4