apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base

namespace: globepay-dev

# Dev-specific configurations
replicas:
- name: backend
  count: 1
- name: frontend
  count: 1