apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
stringData:
  DB_PASSWORD: secure_password_here
  JWT_SECRET: SECURE_JWT_SECRET_KEY
  database-url: postgresql://globepay:secure_password_here@postgresql.globepay-prod.svc.cluster.local:5432/globepay_prod?sslmode=disable