apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
stringData:
  DB_PASSWORD: ${DB_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}
  database-url: postgresql://globepay:${DB_PASSWORD}@postgresql.globepay-prod.svc.cluster.local:5432/globepay_prod?sslmode=disable