apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: postgresql-secrets
    literals:
      - POSTGRES_USER=globepay
      - POSTGRES_PASSWORD=secure_password_here

generatorOptions:
  disableNameSuffixHash: true