apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aws-load-balancer-webhook-cert
  namespace: kube-system
spec:
  secretName: aws-load-balancer-webhook-tls
  issuerRef:
    name: aws-load-balancer-ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - aws-load-balancer-webhook-service.kube-system.svc
  - aws-load-balancer-webhook-service.kube-system.svc.cluster.local
  - aws-load-balancer-webhook-service