apiVersion: v1
kind: Service
metadata:
  name: {{ include "globepay.fullname" . }}-frontend
  labels:
    {{- include "globepay.labels" . | nindent 4 }}
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "globepay.selectorLabels" . | nindent 4 }}
    app: frontend
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}