{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "globepay.fullname" . }}-{{ .Values.redis.name }}
  labels:
    {{- include "globepay.labels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "globepay.selectorLabels" . | nindent 6 }}
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        {{- include "globepay.selectorLabels" . | nindent 8 }}
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.service.port }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        emptyDir: {}
{{- end }}