{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "globepay.fullname" . }}-{{ .Values.redis.name }}
  labels:
    {{- include "globepay.labels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
spec:
  selector:
    {{- include "globepay.selectorLabels" . | nindent 4 }}
    app: {{ .Values.redis.name }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
{{- end }}