{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "globepay.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  database-url: {{ printf "postgresql://globepay:%s@postgresql.%s.svc.cluster.local:5432/%s_%s?sslmode=disable" .Values.secrets.dbPassword .Values.global.namespace .Values.database.name .Values.global.environment | b64enc | quote }}
{{- end }}