apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globepay-backend-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: globepay-project
  source:
    repoURL: https://github.com/leketech/globepay.git
    targetRevision: main
    path: helm/globepay
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: globepay-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/name: globepay-backend-prod
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: batch
    kind: Job
    name: database-migration