apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application.yaml
- application-frontend.yaml
- application-backend-helm.yaml
- application-frontend-helm.yaml
- project.yaml