apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: globepay-prod
  namespace: argocd
spec:
  description: Globepay Production Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: globepay-prod
    server: https://kubernetes.default.svc
  - namespace: globepay-staging
    server: https://kubernetes.default.svc
  - namespace: globepay-dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: developer
    description: Developer role
    policies:
    - p, proj:globepay:developer, applications, get, globepay/*, allow
    - p, proj:globepay:developer, applications, sync, globepay/*, allow
    groups:
    - developers

  - name: admin
    description: Admin role
    policies:
    - p, proj:globepay:admin, applications, *, globepay/*, allow
    groups:
    - admins